const versionOneSchemaValidator = require('./schemas/versionOne');

/**
 * Validates a state machine config object against known schemas.
 * @param {object} machineData A YAML-converted-to-JSON state machine definition
 * @return The state machine if valid
 * @throws Error when validation fails describing the validation error. The message is (most likely)
 *         generated by Joi, so parsing the message may be a little tricky.
 */
async function validateMachineConfig(
    machineData,
    schemaValidators = {
        1: versionOneSchemaValidator,
    },
) {
    if (schemaValidators[machineData.version] === undefined)
        throw new Error(`Unsupported version number: ${machineData.version}`);

    try {
        const result = await schemaValidators[machineData.version](machineData);

        if (result.error) throw result.error;
        return result.value;
    } catch (err) {
        throw err;
    }
}

module.exports = validateMachineConfig;
